# Generated by Django 5.2 on 2025-04-28 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('org_status', models.BooleanField(blank=True, default=False)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('last_auth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
