# Generated by Django 5.2 on 2025-04-29 10:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Здания',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Дата проведения')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_visiable', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='ItemInEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Особенности мероприятий',
                'verbose_name_plural': 'Особенности мероприятий',
            },
        ),
        migrations.CreateModel(
            name='ItemInSpaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Особенности помещения',
                'verbose_name_plural': 'Особенности помещения',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Дополнительная информация о пользователях', 'verbose_name_plural': 'Дополнительная информация о пользователях'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_auth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reg_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='uploads/users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_status',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ImgageForEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads/events/', verbose_name='Изображение')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Изображения мероприятий',
                'verbose_name_plural': 'Изображения мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='items_id',
            field=models.ManyToManyField(to='bron.iteminevents', verbose_name='Особенности'),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Организаторы',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bron.organizer', verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.event', verbose_name='Мероприятие')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрации',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
                ('room_number', models.CharField(max_length=12, verbose_name='Номер помещения')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_visiable', models.BooleanField(default=True, verbose_name='Показывать')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bron.building', verbose_name='Здание')),
                ('items_id', models.ManyToManyField(to='bron.iteminspaces', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Помещения',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='ImgageForSpaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads/spaces/', verbose_name='Изображение')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Изображения помещений',
                'verbose_name_plural': 'Изображения помещений',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('event_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bron.event', verbose_name='Мероприятие')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('space_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bron.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bron.space', verbose_name='Помещение'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_акщь', models.DateField(default=datetime.datetime.today, verbose_name='Дата начала брони')),
                ('book_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.space', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='SpacesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1023, verbose_name='Отзыв')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_visiable', models.BooleanField(default=True, verbose_name='Показывать')),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.space', verbose_name='Помещение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзывы на помещения',
                'verbose_name_plural': 'Отзывы на помещения',
            },
        ),
    ]
