# Generated by Django 5.2 on 2025-05-02 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0004_rename_date_акщь_booking_date_to_booking_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата начала брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата конца брони'),
        ),
    ]
