# Generated by Django 5.2 on 2025-05-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0005_alter_booking_date_from_alter_booking_date_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='patronymic',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='event_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bron.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='space_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bron.space', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='imageforevents',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='bron/uploads/events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageforspaces',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='bron/uploads/spaces/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='bron/uploads/users/', verbose_name='Аватар'),
        ),
    ]
