# Generated by Django 5.2 on 2025-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0006_rename_last_name_profile_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancella',
            field=models.BooleanField(default=False, verbose_name='Отмена брони'),
        ),
    ]
