# Generated by Django 5.2 on 2025-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0007_booking_cancella'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancella',
            new_name='cancellation',
        ),
    ]
