# Generated by Django 5.2 on 2025-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0008_rename_cancella_booking_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancellation',
            field=models.BooleanField(default=False, verbose_name='Отмена регистрации'),
        ),
    ]
