# Generated by Django 5.2 on 2025-05-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0009_registration_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('NB', 'Новая бронь'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='Новая бронь', max_length=20, verbose_name='Статус'),
        ),
    ]
