# Generated by Django 5.2 on 2025-05-13 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0010_remove_booking_cancellation_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата начала брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата конца брони'),
        ),
    ]
