# Generated by Django 5.2 on 2025-05-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0011_alter_booking_book_date_alter_booking_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
