# Generated by Django 5.2 on 2025-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0012_alter_favourite_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
