# Generated by Django 5.2 on 2025-05-13 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0013_alter_event_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата проведения'),
        ),
    ]
