# Generated by Django 5.2 on 2025-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0015_alter_event_description_alter_event_items_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='cancellation',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('NB', 'Новая бронь'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='Новая бронь', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.BooleanField(choices=[('NB', 'Новая регистрация'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='Новая регистрация', verbose_name='Статус'),
        ),
    ]
