# Generated by Django 5.2 on 2025-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0016_remove_registration_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('NR', 'Новая регистрация'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='Новая регистрация', verbose_name='Статус'),
        ),
    ]
