# Generated by Django 5.2 on 2025-05-19 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0017_alter_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата конца брони'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='space',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
