# Generated by Django 5.2 on 2025-05-20 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0018_alter_booking_date_from_alter_booking_date_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-book_date'], 'verbose_name': 'Бронирования', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-add_date'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-reg_date'], 'verbose_name': 'Регистрации', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AlterModelOptions(
            name='spacesreview',
            options={'ordering': ['-add_date'], 'verbose_name': 'Отзывы на помещения', 'verbose_name_plural': 'Отзывы на помещения'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_bookings', to='bron.space', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('NB', 'Новая бронь'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='NB', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='event',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_events', to='bron.organizer', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='space_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='space_events', to='bron.space', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='event_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_event', to='bron.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='imageforevents',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='bron.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='imageforevents',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageforspaces',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='spaces/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageforspaces',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_images', to='bron.space', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_organizers', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reg', to='bron.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('NR', 'Новая регистрация'), ('CBC', 'Отмена ДО подтверждения'), ('C', 'Подтверждена'), ('CAC', 'Отмена ПОСЛЕ подтверждения')], default='NR', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reg', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='spacesreview',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reviews', to='bron.space', verbose_name='Помещение'),
        ),
    ]
