# Generated by Django 5.2 on 2025-05-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0019_alter_booking_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='items_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_books', to='bron.space', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_regs', to='bron.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='EventWithItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.event', verbose_name='Мероприятия')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.iteminevents', verbose_name='Особенность')),
            ],
            options={
                'verbose_name': 'Мероприятия и особенности',
                'verbose_name_plural': 'Мероприятия и особенности',
            },
        ),
    ]
