# Generated by Django 5.2 on 2025-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0020_remove_event_items_id_alter_booking_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='items_id',
            field=models.ManyToManyField(blank=True, through='bron.EventWithItems', through_fields=('event', 'item'), to='bron.iteminevents', verbose_name='Особенности'),
        ),
    ]
