# Generated by Django 5.2 on 2025-05-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0021_event_items_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='events/docs', verbose_name='Приложение'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='charter',
            field=models.FileField(blank=True, null=True, upload_to='orgs/docs', verbose_name='Устав'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
