# Generated by Django 5.2 on 2025-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0022_event_attachment_organizer_charter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Профиль в Telegram'),
        ),
    ]
