# Generated by Django 5.2 on 2025-06-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0023_profile_telegram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_status',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='space_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='bron.space', verbose_name='Помещение'),
        ),
    ]
