# Generated by Django 5.2 on 2025-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0024_profile_admin_status_alter_favourite_space_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='is_visiable',
            field=models.BooleanField(default=False, verbose_name='Показывать'),
        ),
    ]
